"""
FINAL FIX - Professional Legal Documents
- Cream paper background #f7eedf
- User's PNG logo
- ALL text BLACK and consistent size
- Compact formatting (fewer pages)
- Professional appearance
"""
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.oxml import OxmlElement
import os

def set_cream_background(doc):
    """Set cream paper background #f7eedf"""
    try:
        element = doc.element
        sectPr = element.xpath('//w:sectPr')[0]
        bg = sectPr.xpath('./w:background')
        if not bg:
            background = OxmlElement('w:background')
            background.set(qn('w:color'), 'f7eedf')
            sectPr.insert(0, background)
        else:
            bg[0].set(qn('w:color'), 'f7eedf')
    except:
        pass

def add_black_border(section):
    """Simple black border"""
    sectPr = section._sectPr
    pgBorders = sectPr.find(qn('w:pgBorders'))
    if pgBorders is not None:
        sectPr.remove(pgBorders)

    pgBorders = OxmlElement('w:pgBorders')
    sectPr.append(pgBorders)
    pgBorders.set(qn('w:offsetFrom'), 'page')

    for border_name in ['w:top', 'w:left', 'w:bottom', 'w:right']:
        border = OxmlElement(border_name)
        border.set(qn('w:val'), 'single')
        border.set(qn('w:sz'), '20')
        border.set(qn('w:space'), '20')
        border.set(qn('w:color'), '000000')
        pgBorders.append(border)

def add_compact_header(doc, logo_path):
    """Compact header with logo"""
    section = doc.sections[0]
    header = section.header

    for para in list(header.paragraphs):
        p = para._element
        p.getparent().remove(p)

    # Logo
    header_para = header.add_paragraph()
    if os.path.exists(logo_path):
        try:
            run = header_para.add_run()
            run.add_picture(logo_path, width=Inches(1.5))
            header_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
            header_para.space_after = Pt(3)
        except Exception as e:
            print(f"  ⚠️ Logo error: {e}")

    # Small separator
    sep = header.add_paragraph()
    sep_run = sep.add_run("_" * 80)
    sep_run.font.size = Pt(6)
    sep_run.font.color.rgb = RGBColor(0, 0, 0)
    sep.alignment = WD_ALIGN_PARAGRAPH.CENTER
    sep.space_after = Pt(2)

def add_compact_footer(doc):
    """Minimal footer"""
    footer = doc.sections[0].footer
    for para in list(footer.paragraphs):
        p = para._element
        p.getparent().remove(p)

    footer_para = footer.add_paragraph()
    footer_run = footer_para.add_run("Generated by Lawmate")
    footer_run.font.size = Pt(7)
    footer_run.font.color.rgb = RGBColor(80, 80, 80)
    footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

def format_uniform_text(para, is_title=False, is_heading=False):
    """Uniform BLACK text formatting"""
    for run in para.runs:
        run.font.name = 'Times New Roman'
        run.font.color.rgb = RGBColor(0, 0, 0)  # BLACK

        if is_title:
            run.font.size = Pt(13)  # Consistent size
            run.font.bold = True
        elif is_heading:
            run.font.size = Pt(11)  # Consistent size
            run.font.bold = True
        else:
            run.font.size = Pt(11)  # Consistent size
            run.font.bold = False

    # Compact spacing
    if is_title:
        para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        para.space_before = Pt(4)
        para.space_after = Pt(4)
    elif is_heading:
        para.space_before = Pt(4)
        para.space_after = Pt(2)
    else:
        para.paragraph_format.line_spacing = 1.3  # Reduced from 1.5
        para.paragraph_format.space_after = Pt(3)  # Reduced
        para.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY

def fix_document_final(file_path, logo_path):
    """Final professional fix"""
    filename = os.path.basename(file_path)
    print(f"\n🔧 {filename}")

    try:
        doc = Document(file_path)

        # Cream background
        set_cream_background(doc)

        # Compact margins
        for section in doc.sections:
            section.top_margin = Inches(0.8)
            section.bottom_margin = Inches(0.8)
            section.left_margin = Inches(1.0)
            section.right_margin = Inches(1.0)
            add_black_border(section)

        # Header and footer
        add_compact_header(doc, logo_path)
        add_compact_footer(doc)

        # Format all text uniformly
        for i, para in enumerate(doc.paragraphs):
            text = para.text.upper()
            if 'IN THE COURT' in text or (i == 0 and len(para.text) > 20):
                format_uniform_text(para, is_title=True)
            elif any(kw in text for kw in ['APPLICATION FOR', 'PETITION FOR', 'PRAYER:', 'APPLICANT', 'THROUGH COUNSEL']):
                format_uniform_text(para, is_heading=True)
            else:
                format_uniform_text(para)

        # Format tables too
        for table in doc.tables:
            for row in table.rows:
                for cell in row.cells:
                    for para in cell.paragraphs:
                        for run in para.runs:
                            run.font.name = 'Times New Roman'
                            run.font.size = Pt(11)
                            run.font.color.rgb = RGBColor(0, 0, 0)

        doc.save(file_path)
        print(f"  ✅ Done")
        return True
    except Exception as e:
        print(f"  ❌ {e}")
        return False

# Use PNG logo
logo_path = "/Users/mac/Downloads/Copy of Copy of Labor Law Thesis Defense by Slidesgo.pptx.png"

if not os.path.exists(logo_path):
    print(f"⚠️ PNG logo not found at {logo_path}")
    print("Using converted logo instead...")
    logo_path = "./data/user-logo.png"

template_dir = "./data/DOC_TEMPLATE"
templates = [f for f in os.listdir(template_dir) if f.endswith('.docx')]

print("=" * 70)
print("FINAL PROFESSIONAL FIX")
print("=" * 70)
print(f"Logo: {logo_path}")
print(f"Background: #f7eedf (cream)")
print(f"Text: BLACK, consistent 11pt")
print(f"Layout: Compact (fewer pages)")
print(f"\nFixing {len(templates)} templates...\n")

success = 0
for template_file in templates:
    file_path = os.path.join(template_dir, template_file)
    if fix_document_final(file_path, logo_path):
        success += 1

print("\n" + "=" * 70)
print(f"✅ {success}/{len(templates)} templates fixed")
print("\n📋 Final Features:")
print("  ✓ Cream background (#f7eedf)")
print("  ✓ Your PNG logo")
print("  ✓ ALL text BLACK and consistent size (11pt)")
print("  ✓ Compact spacing (fewer pages)")
print("  ✓ Professional legal appearance")
print("=" * 70)
